// @generated by AI Unit Test Agent -- review before merging
import React from 'react';
import { render, screen, fireEvent, act, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom';
import App from './App';

const mockGenerateContent = jest.fn();

jest.mock('@google/generative-ai', () => ({
  GoogleGenerativeAI: function GoogleGenerativeAI() {
    return {
      getGenerativeModel: () => ({
        generateContent: (...args) => mockGenerateContent(...args),
      }),
    };
  },
}));

jest.mock('framer-motion', () => {
  const React = require('react');
  const strip = [
    'initial',
    'animate',
    'exit',
    'transition',
    'whileHover',
    'whileTap',
    'whileInView',
    'variants',
  ];
  return {
    motion: new Proxy(
      {},
      {
        get: (_t, tag) => ({ children, ...rest }) => {
          const props = {};
          Object.keys(rest).forEach((k) => {
            if (!strip.includes(k)) props[k] = rest[k];
          });
          return React.createElement(tag, props, children);
        },
      }
    ),
    AnimatePresence: ({ children }) => React.createElement(React.Fragment, null, children),
  };
});

jest.mock('recharts', () => {
  const React = require('react');
  const box = (name) => ({ children }) =>
    React.createElement('div', { 'data-testid': name }, children);
  return {
    ResponsiveContainer: box('responsive-container'),
    BarChart: box('bar-chart'),
    PieChart: box('pie-chart'),
    Pie: box('pie'),
    Bar: () => null,
    Cell: () => null,
    XAxis: () => null,
    YAxis: () => null,
    CartesianGrid: () => null,
    Tooltip: () => null,
  };
});

const PLACEHOLDER = 'e.g., What is the capital of India?';
const QUIZ_PLACEHOLDER = "Click 'Get Answer' to generate a quiz";

const getSubmit = () => screen.getByRole('button', { name: /Get Answer|Processing/ });
const getHeaderButtons = () => Array.from(document.querySelector('header').querySelectorAll('button'));
const getStatsButton = () => getHeaderButtons()[0];
const getDarkButton = () => getHeaderButtons()[1];

const ask = async (user, question, answerText) => {
  mockGenerateContent.mockResolvedValueOnce({ response: { text: () => answerText } });
  await user.type(screen.getByPlaceholderText(PLACEHOLDER), question);
  await user.click(getSubmit());
  await screen.findByText(answerText);
};

const seedHistory = () => [
  {
    question: 'Older question',
    answer: 'Older answer',
    category: 'History',
    timestamp: '2024-01-01T00:00:00.000Z',
  },
  {
    question: 'Newer question',
    answer: 'Newer answer',
    category: 'Science',
    timestamp: '2024-02-01T00:00:00.000Z',
  },
];

describe('App', () => {
  let alertSpy;
  let confirmSpy;

  beforeEach(() => {
    localStorage.clear();
    mockGenerateContent.mockReset();
    alertSpy = jest.spyOn(window, 'alert').mockImplementation(() => {});
    confirmSpy = jest.spyOn(window, 'confirm').mockImplementation(() => true);
  });

  afterEach(() => {
    jest.useRealTimers();
    jest.restoreAllMocks();
    delete window.speechSynthesis;
    delete window.SpeechSynthesisUtterance;
    delete window.SpeechRecognition;
    delete window.webkitSpeechRecognition;
  });

  describe('initial render and persistence', () => {
    it('should render header, default category, quiz mode OFF and footer on initial load', () => {
      render(<App />);
      expect(screen.getByText('GK Master Pro')).toBeInTheDocument();
      expect(screen.getByText('0 Streak')).toBeInTheDocument();
      expect(screen.getByText('OFF')).toBeInTheDocument();
      expect(screen.getByText('❓ Ask Your Question')).toBeInTheDocument();
      expect(screen.getByText('🚀 Get Answer')).toBeInTheDocument();
      expect(screen.getByPlaceholderText(PLACEHOLDER)).toBeInTheDocument();
      expect(screen.getByText(/Made with/)).toBeInTheDocument();
      expect(screen.queryByText('✨ Answer')).not.toBeInTheDocument();
      expect(screen.queryByText(/Question History/)).not.toBeInTheDocument();
    });

    it('should restore dark mode, history, streak and category stats from localStorage on mount', () => {
      localStorage.setItem('darkMode', 'true');
      localStorage.setItem('history', JSON.stringify(seedHistory()));
      localStorage.setItem('streak', '5');
      localStorage.setItem('categoryStats', JSON.stringify({ History: 1, Science: 1 }));

      const { container } = render(<App />);
      expect(container.firstChild).toHaveClass('dark');
      expect(screen.getByText('5 Streak')).toBeInTheDocument();
      expect(screen.getByText(/Question History \(2\)/)).toBeInTheDocument();
      expect(screen.getByText('Q: Older question')).toBeInTheDocument();
      expect(screen.getByText('Q: Newer question')).toBeInTheDocument();
    });

    it('should fall back to defaults when localStorage is empty', () => {
      const { container } = render(<App />);
      expect(container.firstChild).not.toHaveClass('dark');
      expect(screen.getByText('0 Streak')).toBeInTheDocument();
      expect(screen.queryByText(/Question History/)).not.toBeInTheDocument();
    });

    it('should render history most-recent first with truncated answer', () => {
      const longAnswer = 'x'.repeat(250);
      const items = seedHistory();
      items[1].answer = longAnswer;
      localStorage.setItem('history', JSON.stringify(items));

      render(<App />);
      const questions = screen.getAllByText(/^Q: /);
      expect(questions[0]).toHaveTextContent('Q: Newer question');
      expect(questions[1]).toHaveTextContent('Q: Older question');
      expect(screen.getByText(`A: ${'x'.repeat(200)}...`)).toBeInTheDocument();
    });
  });

  describe('dark mode and input', () => {
    it('should toggle dark mode and persist it to localStorage', async () => {
      const user = userEvent.setup();
      const { container } = render(<App />);

      await user.click(getDarkButton());
      expect(container.firstChild).toHaveClass('dark');
      expect(localStorage.getItem('darkMode')).toBe('true');

      await user.click(getDarkButton());
      expect(container.firstChild).not.toHaveClass('dark');
      expect(localStorage.getItem('darkMode')).toBe('false');
    });

    it('should update the question input as the user types', async () => {
      const user = userEvent.setup();
      render(<App />);
      const input = screen.getByPlaceholderText(PLACEHOLDER);
      await user.type(input, 'Who wrote Hamlet?');
      expect(input).toHaveValue('Who wrote Hamlet?');
    });
  });

  describe('submitting questions', () => {
    it('should alert and not call the API when submitting an empty question', async () => {
      const user = userEvent.setup();
      render(<App />);
      await user.click(getSubmit());
      expect(alertSpy).toHaveBeenCalledWith('Please enter a question!');
      expect(mockGenerateContent).not.toHaveBeenCalled();
      expect(screen.queryByText('✨ Answer')).not.toBeInTheDocument();
    });

    it('should alert and not call the API when submitting a whitespace-only question', async () => {
      const user = userEvent.setup();
      render(<App />);
      await user.type(screen.getByPlaceholderText(PLACEHOLDER), '   ');
      await user.click(getSubmit());
      expect(alertSpy).toHaveBeenCalledWith('Please enter a question!');
      expect(mockGenerateContent).not.toHaveBeenCalled();
    });

    it('should call the model with a category-specific prompt and display the answer on successful submit', async () => {
      const user = userEvent.setup();
      render(<App />);
      await ask(user, 'What is gravity?', 'Gravity is a force.');
      expect(mockGenerateContent).toHaveBeenCalledWith('Answer this General question: What is gravity?');
      expect(screen.getByText('Gravity is a force.')).toBeInTheDocument();
    });

    it('should use the newly selected category in the prompt', async () => {
      const user = userEvent.setup();
      render(<App />);
      await user.click(screen.getByRole('button', { name: /Science/ }));
      await ask(user, 'What is an atom?', 'Smallest unit.');
      expect(mockGenerateContent).toHaveBeenCalledTimes(1);
      expect(mockGenerateContent.mock.calls[0][0]).toMatch(/^Answer this Science question:/);
    });

    it('should show Processing... and disable the submit button while the request is pending', async () => {
      const user = userEvent.setup();
      let resolve;
      mockGenerateContent.mockReturnValueOnce(
        new Promise((r) => {
          resolve = r;
        })
      );
      render(<App />);
      await user.type(screen.getByPlaceholderText(PLACEHOLDER), 'Slow question');
      await user.click(getSubmit());

      expect(screen.getByText(/Processing\.\.\./)).toBeInTheDocument();
      expect(getSubmit()).toBeDisabled();

      await act(async () => {
        resolve({ response: { text: () => 'Done answer' } });
      });

      expect(await screen.findByText('Done answer')).toBeInTheDocument();
      expect(screen.getByText('🚀 Get Answer')).toBeInTheDocument();
      expect(getSubmit()).toBeEnabled();
    });

    it('should add to history, increment streak, update category stats and persist them after a successful answer', async () => {
      const user = userEvent.setup();
      render(<App />);
      await ask(user, 'Capital of France?', 'Paris');

      expect(screen.getByText(/Question History \(1\)/)).toBeInTheDocument();
      expect(screen.getByText('Q: Capital of France?')).toBeInTheDocument();
      expect(screen.getByText('General')).toBeInTheDocument();
      expect(screen.getByText('1 Streak')).toBeInTheDocument();
      expect(screen.getByPlaceholderText(PLACEHOLDER)).toHaveValue('');

      const savedHistory = JSON.parse(localStorage.getItem('history'));
      expect(savedHistory).toHaveLength(1);
      expect(savedHistory[0]).toMatchObject({
        question: 'Capital of France?',
        answer: 'Paris',
        category: 'General',
      });
      expect(JSON.parse(localStorage.getItem('categoryStats'))).toEqual({ General: 1 });
      expect(localStorage.getItem('streak')).toBe('1');
    });

    it('should display an ERROR answer and not add history when the API rejects', async () => {
      const user = userEvent.setup();
      const errorSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
      mockGenerateContent.mockRejectedValueOnce(new Error('boom'));
      render(<App />);
      await user.type(screen.getByPlaceholderText(PLACEHOLDER), 'Will fail');
      await user.click(getSubmit());

      expect(await screen.findByText('ERROR: boom')).toBeInTheDocument();
      expect(errorSpy).toHaveBeenCalled();
      expect(screen.queryByText(/Question History/)).not.toBeInTheDocument();
      expect(getSubmit()).toBeEnabled();
    });
  });

  describe('quiz mode', () => {
    it('should toggle quiz mode, disable the input and hide the microphone button', async () => {
      const user = userEvent.setup();
      render(<App />);
      expect(screen.getByTitle('Voice Input')).toBeInTheDocument();

      await user.click(screen.getByRole('button', { name: 'OFF' }));

      expect(screen.getByRole('button', { name: 'ON' })).toBeInTheDocument();
      expect(screen.getByText('🎲 Generate Quiz Question')).toBeInTheDocument();
      const input = screen.getByPlaceholderText(QUIZ_PLACEHOLDER);
      expect(input).toBeDisabled();
      expect(screen.queryByTitle('Voice Input')).not.toBeInTheDocument();
    });

    it('should send a quiz-generation prompt and record Quiz Question in history in quiz mode', async () => {
      const user = userEvent.setup();
      mockGenerateContent.mockResolvedValueOnce({ response: { text: () => 'Quiz text' } });
      render(<App />);
      await user.type(screen.getByPlaceholderText(PLACEHOLDER), 'seed');
      await user.click(screen.getByRole('button', { name: 'OFF' }));
      await user.click(getSubmit());

      expect(await screen.findByText('Quiz text')).toBeInTheDocument();
      expect(mockGenerateContent.mock.calls[0][0]).toMatch(
        /^Generate a General GK\/GS question with 4 options/
      );
      expect(screen.getByText('Q: Quiz Question')).toBeInTheDocument();
    });
  });

  describe('clear, copy and speech', () => {
    it('should clear question and answer when Clear is clicked', async () => {
      const user = userEvent.setup();
      render(<App />);
      await ask(user, 'First', 'First answer');
      const input = screen.getByPlaceholderText(PLACEHOLDER);
      await user.type(input, 'pending text');
      expect(input).toHaveValue('pending text');

      await user.click(screen.getByRole('button', { name: 'Clear' }));

      expect(input).toHaveValue('');
      expect(screen.queryByText('First answer')).not.toBeInTheDocument();
    });

    it('should cancel speech synthesis when Clear is clicked while speaking', async () => {
      const user = userEvent.setup();
      window.speechSynthesis = { speak: jest.fn(), cancel: jest.fn() };
      window.SpeechSynthesisUtterance = function (text) {
        this.text = text;
      };
      render(<App />);
      await ask(user, 'Q1', 'Speak me');
      await user.click(screen.getByRole('button', { name: 'Speak' }));
      expect(screen.getByRole('button', { name: 'Stop' })).toBeInTheDocument();

      await user.click(screen.getByRole('button', { name: 'Clear' }));
      expect(window.speechSynthesis.cancel).toHaveBeenCalled();

      await ask(user, 'Q2', 'Second answer');
      expect(screen.getByRole('button', { name: 'Speak' })).toBeInTheDocument();
    });

    it('should copy the answer to clipboard and show Copied! that reverts after 2 seconds', async () => {
      const user = userEvent.setup();
      render(<App />);
      await ask(user, 'Copy test', 'Copy this answer');

      const writeText = jest.fn().mockResolvedValue(undefined);
      Object.defineProperty(navigator, 'clipboard', {
        value: { writeText },
        configurable: true,
      });
      jest.useFakeTimers();

      await act(async () => {
        fireEvent.click(screen.getByRole('button', { name: 'Copy' }));
      });

      expect(writeText).toHaveBeenCalledWith('Copy this answer');
      expect(screen.getByRole('button', { name: 'Copied!' })).toBeInTheDocument();

      act(() => {
        jest.advanceTimersByTime(2000);
      });
      expect(screen.getByRole('button', { name: 'Copy' })).toBeInTheDocument();
    });

    it('should start speaking the answer and toggle to Stop, then cancel on second click', async () => {
      const user = userEvent.setup();
      window.speechSynthesis = { speak: jest.fn(), cancel: jest.fn() };
      window.SpeechSynthesisUtterance = function (text) {
        this.text = text;
      };
      render(<App />);
      await ask(user, 'Speech', 'Read aloud');

      await user.click(screen.getByRole('button', { name: 'Speak' }));
      expect(window.speechSynthesis.speak).toHaveBeenCalledTimes(1);
      expect(window.speechSynthesis.speak.mock.calls[0][0].text).toBe('Read aloud');
      expect(screen.getByRole('button', { name: 'Stop' })).toBeInTheDocument();

      await user.click(screen.getByRole('button', { name: 'Stop' }));
      expect(window.speechSynthesis.cancel).toHaveBeenCalled();
      expect(screen.getByRole('button', { name: 'Speak' })).toBeInTheDocument();
    });

    it('should alert when text-to-speech is unsupported', async () => {
      const user = userEvent.setup();
      render(<App />);
      await ask(user, 'Speech', 'No TTS');
      delete window.speechSynthesis;

      await user.click(screen.getByRole('button', { name: 'Speak' }));
      expect(alertSpy).toHaveBeenCalledWith('Text-to-speech not supported');
    });
  });

  describe('voice input', () => {
    it('should start voice recognition and fill the question with the transcript', async () => {
      const user = userEvent.setup();
      let recognition;
      window.SpeechRecognition = jest.fn(function () {
        this.start = jest.fn();
        recognition = this;
      });
      render(<App />);

      await user.click(screen.getByTitle('Voice Input'));
      expect(window.SpeechRecognition).toHaveBeenCalledTimes(1);
      expect(recognition.start).toHaveBeenCalled();

      act(() => recognition.onstart());
      expect(screen.getByText(/Listening\.\.\. Speak now!/)).toBeInTheDocument();

      act(() => recognition.onresult({ results: [[{ transcript: 'Who is the president?' }]] }));
      expect(screen.getByPlaceholderText(PLACEHOLDER)).toHaveValue('Who is the president?');

      act(() => recognition.onend());
      expect(screen.queryByText(/Listening\.\.\. Speak now!/)).not.toBeInTheDocument();
    });

    it('should alert when speech recognition is unsupported', async () => {
      const user = userEvent.setup();
      render(<App />);
      await user.click(screen.getByTitle('Voice Input'));
      expect(alertSpy).toHaveBeenCalledWith('Speech recognition not supported in your browser');
    });
  });

  describe('statistics dashboard', () => {
    it('should show and hide the statistics dashboard when the stats button is clicked', async () => {
      const user = userEvent.setup();
      render(<App />);
      expect(screen.queryByText('Your Statistics')).not.toBeInTheDocument();

      await user.click(getStatsButton());
      expect(screen.getByText('Your Statistics')).toBeInTheDocument();
      expect(screen.getByText('Total Questions')).toBeInTheDocument();
      expect(screen.getByText('Score Points')).toBeInTheDocument();
      expect(screen.getByText('Categories Explored')).toBeInTheDocument();

      await user.click(getStatsButton());
      expect(screen.queryByText('Your Statistics')).not.toBeInTheDocument();
      expect(screen.queryByText('Total Questions')).not.toBeInTheDocument();
    });

    it('should not render charts when category stats are empty', async () => {
      const user = userEvent.setup();
      render(<App />);
      await user.click(getStatsButton());
      expect(screen.queryByText('Questions by Category')).not.toBeInTheDocument();
      expect(screen.queryByText('Category Distribution')).not.toBeInTheDocument();
    });

    it('should render charts and category count when category stats exist', async () => {
      const user = userEvent.setup();
      localStorage.setItem('categoryStats', JSON.stringify({ History: 2, Science: 3 }));
      render(<App />);
      await user.click(getStatsButton());

      expect(screen.getByText('Questions by Category')).toBeInTheDocument();
      expect(screen.getByText('Category Distribution')).toBeInTheDocument();
      expect(screen.getByText('Categories Explored').previousSibling).toHaveTextContent('2');
    });

    it('should clear history, stats and localStorage when Clear All is confirmed', async () => {
      const user = userEvent.setup();
      confirmSpy.mockReturnValue(true);
      localStorage.setItem('history', JSON.stringify(seedHistory()));
      localStorage.setItem('streak', '4');
      localStorage.setItem('categoryStats', JSON.stringify({ History: 1 }));
      render(<App />);
      expect(screen.getByText('4 Streak')).toBeInTheDocument();

      await user.click(getStatsButton());
      await user.click(screen.getByRole('button', { name: 'Clear All' }));

      expect(confirmSpy).toHaveBeenCalled();
      expect(screen.queryByText(/Question History/)).not.toBeInTheDocument();
      expect(screen.getByText('0 Streak')).toBeInTheDocument();
      expect(localStorage.length).toBe(0);
    });

    it('should keep data when Clear All is cancelled', async () => {
      const user = userEvent.setup();
      confirmSpy.mockReturnValue(false);
      localStorage.setItem('history', JSON.stringify(seedHistory()));
      localStorage.setItem('streak', '4');
      render(<App />);

      await user.click(getStatsButton());
      await user.click(screen.getByRole('button', { name: 'Clear All' }));

      expect(screen.getByText(/Question History \(2\)/)).toBeInTheDocument();
      expect(screen.getByText('4 Streak')).toBeInTheDocument();
      expect(localStorage.getItem('streak')).toBe('4');
      expect(localStorage.getItem('history')).not.toBeNull();
    });
  });
});