// @generated by AI Unit Test Agent -- review before merging
import React from 'react';
import { render, screen, fireEvent, act } from '@testing-library/react';
import '@testing-library/jest-dom';
import App from './App';

const mockGenerateContent = jest.fn();

jest.mock('@google/generative-ai', () => ({
  GoogleGenerativeAI: function GoogleGenerativeAI() {
    return {
      getGenerativeModel: () => ({
        generateContent: (...args) => mockGenerateContent(...args),
      }),
    };
  },
}));

jest.mock('framer-motion', () => {
  const React = require('react');
  const strip = [
    'initial',
    'animate',
    'exit',
    'transition',
    'whileHover',
    'whileTap',
    'variants',
    'layout',
  ];
  return {
    motion: new Proxy(
      {},
      {
        get: (_t, tag) => {
          if (typeof tag !== 'string') return undefined;
          return ({ children, ...rest }) => {
            const props = {};
            Object.keys(rest).forEach((k) => {
              if (!strip.includes(k)) props[k] = rest[k];
            });
            return React.createElement(tag, props, children);
          };
        },
      }
    ),
    AnimatePresence: ({ children }) => children,
  };
});

jest.mock('react-icons/fa', () => {
  const React = require('react');
  const make = (name) => () => React.createElement('span', { 'data-testid': name });
  const names = [
    'FaSun',
    'FaMoon',
    'FaCopy',
    'FaVolumeUp',
    'FaStop',
    'FaMicrophone',
    'FaTrophy',
    'FaHistory',
    'FaChartLine',
    'FaRocket',
    'FaFire',
  ];
  const out = {};
  names.forEach((n) => {
    out[n] = make(n);
  });
  return out;
});

jest.mock('recharts', () => {
  const React = require('react');
  const wrap = (name) => ({ children }) =>
    React.createElement('div', { 'data-testid': name }, children);
  const empty = (name) => () => React.createElement('div', { 'data-testid': name });
  return {
    BarChart: wrap('BarChart'),
    Bar: empty('Bar'),
    XAxis: empty('XAxis'),
    YAxis: empty('YAxis'),
    CartesianGrid: empty('CartesianGrid'),
    Tooltip: empty('Tooltip'),
    ResponsiveContainer: wrap('ResponsiveContainer'),
    PieChart: wrap('PieChart'),
    Pie: wrap('Pie'),
    Cell: () => null,
  };
});

const PLACEHOLDER = 'e.g., What is the capital of India?';
const mockResponse = (text) => ({ response: { text: () => text } });

const getInput = () => screen.getByPlaceholderText(PLACEHOLDER);
const getSubmit = () => screen.getByText('🚀 Get Answer').closest('button');
const getStatsButton = () => screen.getByTestId('FaChartLine').closest('button');

const typeQuestion = (value) => {
  fireEvent.change(getInput(), { target: { value } });
};

const submitQuestion = async (value, answerText) => {
  mockGenerateContent.mockResolvedValueOnce(mockResponse(answerText));
  typeQuestion(value);
  await act(async () => {
    fireEvent.click(getSubmit());
  });
  await screen.findByText(answerText);
};

const seededHistory = (n = 2) =>
  Array.from({ length: n }, (_, i) => ({
    question: `Seed question ${i + 1}`,
    answer: `Seed answer ${i + 1}`,
    category: 'General',
    timestamp: new Date(2024, 0, i + 1).toISOString(),
  }));

describe('App', () => {
  let speechSynthesisMock;

  beforeEach(() => {
    localStorage.clear();
    mockGenerateContent.mockReset();
    mockGenerateContent.mockResolvedValue(mockResponse('Default answer'));
    window.alert = jest.fn();
    window.confirm = jest.fn(() => true);
    speechSynthesisMock = { speak: jest.fn(), cancel: jest.fn() };
    window.speechSynthesis = speechSynthesisMock;
    window.SpeechSynthesisUtterance = jest.fn(function (text) {
      this.text = text;
    });
    Object.defineProperty(navigator, 'clipboard', {
      value: { writeText: jest.fn(() => Promise.resolve()) },
      configurable: true,
      writable: true,
    });
  });

  afterEach(() => {
    jest.useRealTimers();
    delete window.speechSynthesis;
    delete window.SpeechSynthesisUtterance;
    delete window.SpeechRecognition;
    delete window.webkitSpeechRecognition;
  });

  it('should render the header, categories, input form and footer with default state', () => {
    render(<App />);
    expect(screen.getByText('GK Master Pro')).toBeInTheDocument();
    ['General', 'History', 'Geography', 'Science', 'Sports', 'Technology'].forEach((name) => {
      expect(screen.getByText(name)).toBeInTheDocument();
    });
    expect(screen.getByText(/Quiz Mode/)).toBeInTheDocument();
    expect(screen.getByText('0 Streak')).toBeInTheDocument();
    expect(getInput()).toBeInTheDocument();
    expect(screen.getByText('🚀 Get Answer')).toBeInTheDocument();
    expect(screen.getByText('Clear')).toBeInTheDocument();
    expect(screen.getByText(/Made with/)).toBeInTheDocument();
    expect(screen.queryByText('✨ Answer')).not.toBeInTheDocument();
    expect(screen.queryByText(/Question History/)).not.toBeInTheDocument();
  });

  it('should load dark mode, history, stats, score and streak from localStorage on mount', () => {
    localStorage.setItem('darkMode', 'true');
    localStorage.setItem('history', JSON.stringify(seededHistory(3)));
    localStorage.setItem('streak', '5');
    const { container } = render(<App />);
    expect(container.firstChild).toHaveClass('dark');
    expect(screen.getByText('5 Streak')).toBeInTheDocument();
    expect(screen.getByText('Question History (3)')).toBeInTheDocument();
  });

  it('should fall back to defaults when localStorage is empty', () => {
    const { container } = render(<App />);
    expect(container.firstChild).not.toHaveClass('dark');
    expect(screen.getByText('0 Streak')).toBeInTheDocument();
    expect(screen.queryByText(/Question History/)).not.toBeInTheDocument();
  });

  it('should toggle dark mode and persist it to localStorage', () => {
    const { container } = render(<App />);
    fireEvent.click(screen.getByTestId('FaMoon').closest('button'));
    expect(container.firstChild).toHaveClass('dark');
    expect(localStorage.getItem('darkMode')).toBe('true');

    fireEvent.click(screen.getByTestId('FaSun').closest('button'));
    expect(container.firstChild).not.toHaveClass('dark');
    expect(localStorage.getItem('darkMode')).toBe('false');
  });

  it('should switch the selected category when a category button is clicked', () => {
    render(<App />);
    const general = screen.getByText('General').closest('button');
    const historyBtn = screen.getByText('History').closest('button');
    expect(general).toHaveClass('bg-blue-500');
    expect(historyBtn).not.toHaveClass('bg-purple-500');

    fireEvent.click(historyBtn);
    expect(historyBtn).toHaveClass('bg-purple-500');
    expect(general).not.toHaveClass('bg-blue-500');
  });

  it('should alert and not call the model when submitting an empty question', () => {
    render(<App />);
    fireEvent.click(getSubmit());
    expect(window.alert).toHaveBeenCalledWith('Please enter a question!');
    expect(mockGenerateContent).not.toHaveBeenCalled();
  });

  it('should alert and not call the model when submitting a whitespace-only question', () => {
    render(<App />);
    typeQuestion('    ');
    fireEvent.click(getSubmit());
    expect(window.alert).toHaveBeenCalledWith('Please enter a question!');
    expect(mockGenerateContent).not.toHaveBeenCalled();
  });

  it('should update the input value as the user types', () => {
    render(<App />);
    typeQuestion('Who wrote Hamlet?');
    expect(getInput()).toHaveValue('Who wrote Hamlet?');
  });

  it('should submit the question to Gemini with the category prompt and display the answer', async () => {
    render(<App />);
    await submitQuestion('What is 2+2?', 'It is four');
    expect(mockGenerateContent).toHaveBeenCalledWith('Answer this General question: What is 2+2?');
    expect(screen.getByText('It is four')).toBeInTheDocument();
  });

  it('should use the selected category in the prompt', async () => {
    render(<App />);
    fireEvent.click(screen.getByText('Science').closest('button'));
    await submitQuestion('What is an atom?', 'Smallest unit');
    expect(mockGenerateContent).toHaveBeenCalledWith('Answer this Science question: What is an atom?');
  });

  it('should show Processing... and disable the submit button while the request is pending', async () => {
    let resolveRequest;
    mockGenerateContent.mockReturnValue(
      new Promise((resolve) => {
        resolveRequest = resolve;
      })
    );
    render(<App />);
    typeQuestion('Pending question');
    fireEvent.click(getSubmit());

    const processing = await screen.findByText('Processing...');
    expect(processing.closest('button')).toBeDisabled();

    await act(async () => {
      resolveRequest(mockResponse('Finished answer'));
    });
    expect(await screen.findByText('Finished answer')).toBeInTheDocument();
    expect(screen.queryByText('Processing...')).not.toBeInTheDocument();
    expect(getSubmit()).toBeEnabled();
  });

  it('should clear the input, increment streak, and persist history and stats after a successful answer', async () => {
    render(<App />);
    await submitQuestion('Capital of France?', 'Paris');

    expect(getInput()).toHaveValue('');
    expect(screen.getByText('1 Streak')).toBeInTheDocument();

    const history = JSON.parse(localStorage.getItem('history'));
    expect(history).toHaveLength(1);
    expect(history[0]).toEqual(
      expect.objectContaining({
        question: 'Capital of France?',
        answer: 'Paris',
        category: 'General',
        timestamp: expect.any(String),
      })
    );
    expect(JSON.parse(localStorage.getItem('categoryStats'))).toEqual({ General: 1 });
    expect(localStorage.getItem('streak')).toBe('1');
  });

  it('should show an error message and log the error when the API call fails', async () => {
    const errorSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
    mockGenerateContent.mockRejectedValue(new Error('boom'));
    render(<App />);
    typeQuestion('Will fail');
    await act(async () => {
      fireEvent.click(getSubmit());
    });

    expect(await screen.findByText('ERROR: boom')).toBeInTheDocument();
    expect(errorSpy).toHaveBeenCalled();
    expect(getSubmit()).toBeEnabled();
    expect(screen.getByText('0 Streak')).toBeInTheDocument();
    expect(localStorage.getItem('history')).toBeNull();
    errorSpy.mockRestore();
  });

  it('should append to existing history and show newest entries first', async () => {
    render(<App />);
    await submitQuestion('First one', 'Answer one');
    await submitQuestion('Second one', 'Answer two');

    expect(screen.getByText('Question History (2)')).toBeInTheDocument();
    const items = screen.getAllByText(/Q: /);
    expect(items).toHaveLength(2);
    expect(items[0].textContent).toContain('Second one');
    expect(items[1].textContent).toContain('First one');
  });

  it('should truncate history answers to 200 characters followed by an ellipsis', () => {
    const longAnswer = 'a'.repeat(300);
    localStorage.setItem(
      'history',
      JSON.stringify([
        {
          question: 'Long?',
          answer: longAnswer,
          category: 'General',
          timestamp: new Date().toISOString(),
        },
      ])
    );
    render(<App />);
    expect(screen.getByText('A: ' + 'a'.repeat(200) + '...')).toBeInTheDocument();
  });

  it('should toggle quiz mode, disable the input and hide the voice button', () => {
    render(<App />);
    expect(screen.getByTitle('Voice Input')).toBeInTheDocument();
    fireEvent.click(screen.getByText('OFF'));

    expect(screen.getByText('ON')).toBeInTheDocument();
    const input = screen.getByPlaceholderText("Click 'Get Answer' to generate a quiz");
    expect(input).toBeDisabled();
    expect(screen.getByText('🎲 Generate Quiz Question')).toBeInTheDocument();
    expect(screen.queryByTitle('Voice Input')).not.toBeInTheDocument();
  });

  it('should send the quiz-generation prompt and record Quiz Question in history when in quiz mode', async () => {
    mockGenerateContent.mockResolvedValue(mockResponse('Quiz content here'));
    render(<App />);
    typeQuestion('anything');
    fireEvent.click(screen.getByText('OFF'));
    await act(async () => {
      fireEvent.click(getSubmit());
    });
    await screen.findByText('Quiz content here');

    expect(mockGenerateContent).toHaveBeenCalledWith(
      expect.stringMatching(/^Generate a General GK\/GS question with 4 options/)
    );
    const history = JSON.parse(localStorage.getItem('history'));
    expect(history[0].question).toBe('Quiz Question');
  });

  it('should clear input and answer when Clear is clicked', async () => {
    render(<App />);
    await submitQuestion('Some question', 'Some answer');
    typeQuestion('typed again');
    expect(getInput()).toHaveValue('typed again');

    fireEvent.click(screen.getByText('Clear'));
    expect(getInput()).toHaveValue('');
    expect(screen.queryByText('Some answer')).not.toBeInTheDocument();
  });

  it('should cancel speech synthesis when Clear is clicked while speaking', async () => {
    render(<App />);
    await submitQuestion('Speak question', 'Speakable answer');
    fireEvent.click(screen.getByText('Speak'));
    expect(screen.getByText('Stop')).toBeInTheDocument();

    fireEvent.click(screen.getByText('Clear'));
    expect(speechSynthesisMock.cancel).toHaveBeenCalled();
    expect(screen.queryByText('Stop')).not.toBeInTheDocument();
  });

  it('should copy the answer to the clipboard and show Copied! for 2 seconds', async () => {
    render(<App />);
    await submitQuestion('Copy question', 'Copy this answer');

    jest.useFakeTimers();
    await act(async () => {
      fireEvent.click(screen.getByText('Copy'));
    });
    expect(navigator.clipboard.writeText).toHaveBeenCalledWith('Copy this answer');
    expect(screen.getByText('Copied!')).toBeInTheDocument();

    act(() => {
      jest.advanceTimersByTime(2000);
    });
    expect(screen.getByText('Copy')).toBeInTheDocument();
    expect(screen.queryByText('Copied!')).not.toBeInTheDocument();
  });

  it('should speak the answer and toggle to Stop, then cancel on second click', async () => {
    render(<App />);
    await submitQuestion('Talk', 'Spoken answer');

    fireEvent.click(screen.getByText('Speak'));
    expect(speechSynthesisMock.speak).toHaveBeenCalledTimes(1);
    const utterance = window.SpeechSynthesisUtterance.mock.instances[0];
    expect(utterance.text).toBe('Spoken answer');
    expect(utterance.rate).toBe(0.9);
    expect(screen.getByText('Stop')).toBeInTheDocument();

    fireEvent.click(screen.getByText('Stop'));
    expect(speechSynthesisMock.cancel).toHaveBeenCalled();
    expect(screen.getByText('Speak')).toBeInTheDocument();
  });

  it('should return the button to Speak when the utterance ends', async () => {
    render(<App />);
    await submitQuestion('Talk', 'Ending answer');
    fireEvent.click(screen.getByText('Speak'));
    expect(screen.getByText('Stop')).toBeInTheDocument();

    const utterance = window.SpeechSynthesisUtterance.mock.instances[0];
    act(() => {
      utterance.onend();
    });
    expect(screen.getByText('Speak')).toBeInTheDocument();
  });

  it('should alert when text-to-speech is not supported', async () => {
    render(<App />);
    await submitQuestion('Talk', 'No tts answer');
    delete window.speechSynthesis;

    fireEvent.click(screen.getByText('Speak'));
    expect(window.alert).toHaveBeenCalledWith('Text-to-speech not supported');
  });

  it('should start speech recognition, show the listening indicator, then put the transcript into the input', () => {
    let recognition;
    window.SpeechRecognition = jest.fn(function () {
      this.start = jest.fn();
      recognition = this;
    });
    render(<App />);
    fireEvent.click(screen.getByTitle('Voice Input'));
    expect(recognition.start).toHaveBeenCalled();

    act(() => {
      recognition.onstart();
    });
    expect(screen.getByText(/Listening\.\.\. Speak now!/)).toBeInTheDocument();

    act(() => {
      recognition.onresult({ results: [[{ transcript: 'hello world' }]] });
    });
    expect(getInput()).toHaveValue('hello world');

    act(() => {
      recognition.onend();
    });
    expect(screen.queryByText(/Listening\.\.\. Speak now!/)).not.toBeInTheDocument();
  });

  it('should alert when speech recognition is not supported', () => {
    render(<App />);
    fireEvent.click(screen.getByTitle('Voice Input'));
    expect(window.alert).toHaveBeenCalledWith('Speech recognition not supported in your browser');
  });

  it('should show and hide the statistics dashboard when the stats button is clicked', () => {
    render(<App />);
    expect(screen.queryByText('Your Statistics')).not.toBeInTheDocument();

    fireEvent.click(getStatsButton());
    expect(screen.getByText('Your Statistics')).toBeInTheDocument();
    expect(screen.getByText('Total Questions')).toBeInTheDocument();
    expect(screen.getByText('Score Points')).toBeInTheDocument();
    expect(screen.getByText('Categories Explored')).toBeInTheDocument();

    fireEvent.click(getStatsButton());
    expect(screen.queryByText('Your Statistics')).not.toBeInTheDocument();
  });

  it('should not render charts when there are no stats', () => {
    render(<App />);
    fireEvent.click(getStatsButton());
    expect(screen.queryByText('Questions by Category')).not.toBeInTheDocument();
    expect(screen.queryByText('Category Distribution')).not.toBeInTheDocument();
    expect(screen.getByText('Categories Explored').previousSibling).toHaveTextContent('0');
  });

  it('should display the number of explored categories and render charts when stats exist', () => {
    localStorage.setItem('categoryStats', JSON.stringify({ History: 1, Science: 2 }));
    render(<App />);
    fireEvent.click(getStatsButton());

    expect(screen.getByText('Questions by Category')).toBeInTheDocument();
    expect(screen.getByText('Category Distribution')).toBeInTheDocument();
    expect(screen.getByText('Categories Explored').previousSibling).toHaveTextContent('2');
  });

  it('should clear all state and localStorage when Clear All is confirmed', () => {
    localStorage.setItem('streak', '5');
    localStorage.setItem('history', JSON.stringify(seededHistory(2)));
    localStorage.setItem('categoryStats', JSON.stringify({ General: 2 }));
    window.confirm = jest.fn(() => true);
    render(<App />);
    expect(screen.getByText('5 Streak')).toBeInTheDocument();

    fireEvent.click(getStatsButton());
    fireEvent.click(screen.getByText('Clear All'));

    expect(window.confirm).toHaveBeenCalled();
    expect(screen.getByText('0 Streak')).toBeInTheDocument();
    expect(screen.queryByText(/Question History/)).not.toBeInTheDocument();
    expect(localStorage.length).toBe(0);
  });

  it('should keep data when Clear All is cancelled', () => {
    localStorage.setItem('streak', '5');
    localStorage.setItem('history', JSON.stringify(seededHistory(2)));
    window.confirm = jest.fn(() => false);
    render(<App />);

    fireEvent.click(getStatsButton());
    fireEvent.click(screen.getByText('Clear All'));

    expect(window.confirm).toHaveBeenCalled();
    expect(screen.getByText('5 Streak')).toBeInTheDocument();
    expect(screen.getByText('Question History (2)')).toBeInTheDocument();
    expect(localStorage.getItem('streak')).toBe('5');
    expect(JSON.parse(localStorage.getItem('history'))).toHaveLength(2);
  });
});