// @generated by AI Unit Test Agent -- review before merging
import React from 'react';
import { render, screen, fireEvent, act } from '@testing-library/react';
import '@testing-library/jest-dom';
import App from './App';

const mockGenerateContent = jest.fn();

jest.mock('@google/generative-ai', () => ({
  GoogleGenerativeAI: class {
    getGenerativeModel() {
      return {
        generateContent: (...args) => mockGenerateContent(...args),
      };
    }
  },
}));

jest.mock('framer-motion', () => {
  const React = require('react');
  const MOTION_PROPS = ['initial', 'animate', 'exit', 'transition', 'whileHover', 'whileTap'];
  const cache = {};
  return {
    motion: new Proxy(
      {},
      {
        get: (_t, tag) => {
          if (!cache[tag]) {
            cache[tag] = React.forwardRef(({ children, ...rest }, ref) => {
              const props = {};
              Object.keys(rest).forEach((k) => {
                if (!MOTION_PROPS.includes(k)) props[k] = rest[k];
              });
              return React.createElement(tag, { ...props, ref }, children);
            });
          }
          return cache[tag];
        },
      }
    ),
    AnimatePresence: ({ children }) => children,
  };
});

jest.mock('recharts', () => {
  const React = require('react');
  const passthrough = (name) => ({ children }) =>
    React.createElement('div', { 'data-testid': `chart-${name}` }, children);
  return {
    ResponsiveContainer: passthrough('container'),
    BarChart: passthrough('bar-chart'),
    PieChart: passthrough('pie-chart'),
    Pie: passthrough('pie'),
    Bar: () => null,
    Cell: () => null,
    XAxis: () => null,
    YAxis: () => null,
    CartesianGrid: () => null,
    Tooltip: () => null,
  };
});

jest.mock('react-icons/fa', () => {
  const React = require('react');
  const names = [
    'FaSun', 'FaMoon', 'FaCopy', 'FaVolumeUp', 'FaStop', 'FaMicrophone',
    'FaTrophy', 'FaHistory', 'FaChartLine', 'FaRocket', 'FaFire',
  ];
  const icons = {};
  names.forEach((name) => {
    icons[name] = () => React.createElement('span', { 'data-testid': `icon-${name}` });
  });
  return icons;
});

const mockWriteText = jest.fn();
let recognitionInstance;
let setItemSpy;
let clearSpy;
let alertSpy;
let confirmSpy;

const seedHistory = (items) => localStorage.setItem('history', JSON.stringify(items));

const makeItem = (overrides = {}) => ({
  question: 'Old question',
  answer: 'Old answer',
  category: 'General',
  timestamp: '2024-01-01T00:00:00.000Z',
  ...overrides,
});

const mockAnswer = (text) =>
  mockGenerateContent.mockResolvedValue({ response: { text: () => text } });

const ask = async (text) => {
  fireEvent.change(screen.getByRole('textbox'), { target: { value: text } });
  await act(async () => {
    fireEvent.click(screen.getByRole('button', { name: /Get Answer/ }));
  });
};

const statsButton = () => screen.getByTestId('icon-FaChartLine').closest('button');

beforeEach(() => {
  localStorage.clear();
  mockGenerateContent.mockReset();
  mockWriteText.mockReset();
  mockWriteText.mockResolvedValue(undefined);

  setItemSpy = jest.spyOn(Storage.prototype, 'setItem');
  clearSpy = jest.spyOn(Storage.prototype, 'clear');
  alertSpy = jest.spyOn(window, 'alert').mockImplementation(() => {});
  confirmSpy = jest.spyOn(window, 'confirm').mockImplementation(() => true);

  Object.defineProperty(navigator, 'clipboard', {
    value: { writeText: mockWriteText },
    configurable: true,
    writable: true,
  });

  Object.defineProperty(window, 'speechSynthesis', {
    value: { speak: jest.fn(), cancel: jest.fn() },
    configurable: true,
    writable: true,
  });
  window.SpeechSynthesisUtterance = jest.fn(function (text) {
    this.text = text;
  });

  recognitionInstance = undefined;
  window.SpeechRecognition = jest.fn(function () {
    recognitionInstance = this;
    this.start = jest.fn();
  });
  delete window.webkitSpeechRecognition;
});

afterEach(() => {
  jest.useRealTimers();
  jest.restoreAllMocks();
});

describe('App', () => {
  describe('initial render and persistence', () => {
    it('should render header, default category, quiz mode OFF and 0 streak on initial load', () => {
      render(<App />);

      expect(screen.getByText('GK Master Pro')).toBeInTheDocument();
      expect(screen.getByText('0 Streak')).toBeInTheDocument();
      expect(screen.getByRole('button', { name: 'OFF' })).toBeInTheDocument();
      expect(screen.getByPlaceholderText('e.g., What is the capital of India?')).toBeInTheDocument();
      expect(screen.getByRole('button', { name: /🚀 Get Answer/ })).toBeInTheDocument();
      expect(screen.queryByText('✨ Answer')).not.toBeInTheDocument();
      expect(screen.queryByText(/Question History/)).not.toBeInTheDocument();
    });

    it('should restore dark mode, history, stats and streak from localStorage on mount', () => {
      localStorage.setItem('darkMode', 'true');
      localStorage.setItem('streak', '3');
      seedHistory([makeItem({ question: 'First' }), makeItem({ question: 'Second' })]);

      const { container } = render(<App />);

      expect(container.firstChild).toHaveClass('dark');
      expect(screen.getByText('3 Streak')).toBeInTheDocument();
      expect(screen.getByText(/Question History \(2\)/)).toBeInTheDocument();
      expect(screen.getByText('Q: First')).toBeInTheDocument();
      expect(screen.getByText('Q: Second')).toBeInTheDocument();
    });

    it('should use defaults when localStorage is empty', () => {
      const { container } = render(<App />);

      expect(container.firstChild).not.toHaveClass('dark');
      expect(screen.getByText('0 Streak')).toBeInTheDocument();
      expect(screen.queryByText(/Question History/)).not.toBeInTheDocument();
    });
  });

  describe('dark mode, categories and quiz mode', () => {
    it('should toggle dark mode and persist it to localStorage', () => {
      const { container } = render(<App />);
      const toggle = screen.getByTestId('icon-FaMoon').closest('button');

      fireEvent.click(toggle);
      expect(container.firstChild).toHaveClass('dark');
      expect(setItemSpy).toHaveBeenCalledWith('darkMode', true);

      fireEvent.click(screen.getByTestId('icon-FaSun').closest('button'));
      expect(container.firstChild).not.toHaveClass('dark');
      expect(setItemSpy).toHaveBeenCalledWith('darkMode', false);
    });

    it('should switch the selected category when a category button is clicked', () => {
      render(<App />);
      const general = screen.getByRole('button', { name: /General/ });
      const science = screen.getByRole('button', { name: /Science/ });

      expect(general).toHaveClass('bg-blue-500');
      expect(science).not.toHaveClass('bg-red-500');

      fireEvent.click(science);

      expect(screen.getByRole('button', { name: /Science/ })).toHaveClass('bg-red-500');
      expect(screen.getByRole('button', { name: /General/ })).not.toHaveClass('bg-blue-500');
    });

    it('should toggle quiz mode, disabling the input and hiding the voice button', () => {
      render(<App />);
      expect(screen.getByTitle('Voice Input')).toBeInTheDocument();

      fireEvent.click(screen.getByRole('button', { name: 'OFF' }));

      expect(screen.getByRole('button', { name: 'ON' })).toBeInTheDocument();
      expect(screen.getByRole('textbox')).toBeDisabled();
      expect(screen.getByText('🎲 Generate Quiz Question')).toBeInTheDocument();
      expect(screen.queryByTitle('Voice Input')).not.toBeInTheDocument();
    });
  });

  describe('submitting questions', () => {
    it('should alert and not call the API when submitting an empty question', () => {
      render(<App />);

      fireEvent.click(screen.getByRole('button', { name: /Get Answer/ }));

      expect(alertSpy).toHaveBeenCalledWith('Please enter a question!');
      expect(mockGenerateContent).not.toHaveBeenCalled();
    });

    it('should alert and not call the API when submitting a whitespace question', async () => {
      render(<App />);

      await ask('    ');

      expect(alertSpy).toHaveBeenCalledWith('Please enter a question!');
      expect(mockGenerateContent).not.toHaveBeenCalled();
    });

    it('should submit a question, show the answer, and update history, stats and streak', async () => {
      mockAnswer('New Delhi');
      render(<App />);

      await ask('Capital of India?');

      expect(mockGenerateContent).toHaveBeenCalledWith('Answer this General question: Capital of India?');
      expect(await screen.findByText('New Delhi')).toBeInTheDocument();
      expect(screen.getByRole('textbox')).toHaveValue('');
      expect(screen.getByText(/Question History \(1\)/)).toBeInTheDocument();
      expect(screen.getByText('1 Streak')).toBeInTheDocument();

      expect(JSON.parse(localStorage.getItem('history'))).toHaveLength(1);
      expect(JSON.parse(localStorage.getItem('categoryStats'))).toEqual({ General: 1 });
      expect(setItemSpy).toHaveBeenCalledWith('streak', 1);
    });

    it('should include the selected category in the prompt', async () => {
      mockAnswer('Some history');
      render(<App />);

      fireEvent.click(screen.getByRole('button', { name: /History/ }));
      await ask('Who built the Taj Mahal?');

      expect(mockGenerateContent).toHaveBeenCalledTimes(1);
      expect(mockGenerateContent.mock.calls[0][0]).toContain('Answer this History question:');
    });

    it('should reject quiz submission when the question is empty', () => {
      render(<App />);

      fireEvent.click(screen.getByRole('button', { name: 'OFF' }));
      fireEvent.click(screen.getByRole('button', { name: /Get Answer/ }));

      expect(alertSpy).toHaveBeenCalledWith('Please enter a question!');
      expect(mockGenerateContent).not.toHaveBeenCalled();
    });

    it('should use the quiz prompt and record "Quiz Question" in history when quiz mode is on', async () => {
      mockAnswer('Question: ...\nCorrect Answer: A');
      render(<App />);

      fireEvent.change(screen.getByRole('textbox'), { target: { value: 'seed question' } });
      fireEvent.click(screen.getByRole('button', { name: 'OFF' }));
      await act(async () => {
        fireEvent.click(screen.getByRole('button', { name: /Get Answer/ }));
      });

      expect(mockGenerateContent).toHaveBeenCalledTimes(1);
      expect(
        mockGenerateContent.mock.calls[0][0].startsWith('Generate a General GK/GS question with 4 options')
      ).toBe(true);
      expect(await screen.findByText('Q: Quiz Question')).toBeInTheDocument();
    });

    it('should show loading state while the request is pending', async () => {
      let resolveRequest;
      mockGenerateContent.mockReturnValue(
        new Promise((resolve) => {
          resolveRequest = resolve;
        })
      );
      render(<App />);

      await ask('Pending question');

      const processing = screen.getByRole('button', { name: /Processing/ });
      expect(processing).toBeDisabled();

      await act(async () => {
        resolveRequest({ response: { text: () => 'done' } });
      });

      expect(await screen.findByText('done')).toBeInTheDocument();
      expect(screen.getByRole('button', { name: /🚀 Get Answer/ })).toBeEnabled();
      expect(screen.queryByText('Processing...')).not.toBeInTheDocument();
    });

    it('should display an error message when the API call fails', async () => {
      const errorSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
      mockGenerateContent.mockRejectedValue(new Error('boom'));
      render(<App />);

      await ask('Will fail');

      expect(await screen.findByText('ERROR: boom')).toBeInTheDocument();
      expect(errorSpy).toHaveBeenCalled();
      expect(screen.getByRole('button', { name: /🚀 Get Answer/ })).toBeEnabled();
      expect(screen.queryByText(/Question History/)).not.toBeInTheDocument();
      expect(screen.getByText('0 Streak')).toBeInTheDocument();
    });
  });

  describe('answer actions', () => {
    it('should clear question and answer when Clear is clicked', async () => {
      mockAnswer('Some answer');
      render(<App />);
      await ask('Q1');
      await screen.findByText('Some answer');

      fireEvent.change(screen.getByRole('textbox'), { target: { value: 'typed again' } });
      fireEvent.click(screen.getByRole('button', { name: 'Clear' }));

      expect(screen.getByRole('textbox')).toHaveValue('');
      expect(screen.queryByText('Some answer')).not.toBeInTheDocument();
    });

    it('should cancel speech on Clear if currently speaking', async () => {
      mockAnswer('Speakable answer');
      render(<App />);
      await ask('Q1');
      await screen.findByText('Speakable answer');

      fireEvent.click(screen.getByRole('button', { name: /Speak/ }));
      expect(screen.getByRole('button', { name: /Stop/ })).toBeInTheDocument();

      fireEvent.click(screen.getByRole('button', { name: 'Clear' }));
      expect(window.speechSynthesis.cancel).toHaveBeenCalled();
      expect(screen.queryByText('Stop')).not.toBeInTheDocument();

      await ask('Q2');
      expect(await screen.findByRole('button', { name: /Speak/ })).toBeInTheDocument();
    });

    it('should copy the answer to the clipboard and show "Copied!" temporarily', async () => {
      mockAnswer('Copy me');
      render(<App />);
      await ask('Q1');
      await screen.findByText('Copy me');

      jest.useFakeTimers();

      await act(async () => {
        fireEvent.click(screen.getByRole('button', { name: /Copy/ }));
      });

      expect(mockWriteText).toHaveBeenCalledWith('Copy me');
      expect(screen.getByRole('button', { name: /Copied!/ })).toBeInTheDocument();

      act(() => {
        jest.advanceTimersByTime(2000);
      });

      expect(screen.getByRole('button', { name: 'Copy' })).toBeInTheDocument();
      expect(screen.queryByText('Copied!')).not.toBeInTheDocument();
    });

    it('should speak the answer and toggle to Stop, then cancel on second click', async () => {
      mockAnswer('Read this');
      render(<App />);
      await ask('Q1');
      await screen.findByText('Read this');

      fireEvent.click(screen.getByRole('button', { name: /Speak/ }));

      expect(window.speechSynthesis.speak).toHaveBeenCalledTimes(1);
      const utterance = window.speechSynthesis.speak.mock.calls[0][0];
      expect(utterance.text).toBe('Read this');
      expect(screen.getByRole('button', { name: /Stop/ })).toBeInTheDocument();

      fireEvent.click(screen.getByRole('button', { name: /Stop/ }));
      expect(window.speechSynthesis.cancel).toHaveBeenCalledTimes(1);
      expect(screen.getByRole('button', { name: /Speak/ })).toBeInTheDocument();

      fireEvent.click(screen.getByRole('button', { name: /Speak/ }));
      expect(screen.getByRole('button', { name: /Stop/ })).toBeInTheDocument();
      const secondUtterance = window.speechSynthesis.speak.mock.calls[1][0];
      act(() => {
        secondUtterance.onend();
      });
      expect(screen.getByRole('button', { name: /Speak/ })).toBeInTheDocument();
    });

    it('should alert when speech synthesis is unsupported', async () => {
      mockAnswer('No speech');
      render(<App />);
      await ask('Q1');
      await screen.findByText('No speech');

      delete window.speechSynthesis;
      fireEvent.click(screen.getByRole('button', { name: /Speak/ }));

      expect(alertSpy).toHaveBeenCalledWith('Text-to-speech not supported');
    });
  });

  describe('voice input', () => {
    it('should start voice recognition and fill the input with the transcript', () => {
      render(<App />);

      fireEvent.click(screen.getByTitle('Voice Input'));
      expect(recognitionInstance).toBeDefined();
      expect(recognitionInstance.start).toHaveBeenCalled();

      act(() => {
        recognitionInstance.onstart();
      });
      expect(screen.getByText(/Listening\.\.\. Speak now!/)).toBeInTheDocument();

      act(() => {
        recognitionInstance.onresult({ results: [[{ transcript: 'what is gravity' }]] });
      });
      expect(screen.getByRole('textbox')).toHaveValue('what is gravity');

      act(() => {
        recognitionInstance.onend();
      });
      expect(screen.queryByText(/Listening\.\.\. Speak now!/)).not.toBeInTheDocument();
    });

    it('should alert when speech recognition is unsupported', () => {
      delete window.SpeechRecognition;
      delete window.webkitSpeechRecognition;
      render(<App />);

      fireEvent.click(screen.getByTitle('Voice Input'));

      expect(alertSpy).toHaveBeenCalledWith('Speech recognition not supported in your browser');
    });
  });

  describe('stats dashboard', () => {
    it('should show and hide the stats dashboard via the stats button', () => {
      render(<App />);
      expect(screen.queryByText('Your Statistics')).not.toBeInTheDocument();

      fireEvent.click(statsButton());
      expect(screen.getByText('Your Statistics')).toBeInTheDocument();
      expect(screen.getByText('Total Questions')).toBeInTheDocument();
      expect(screen.getByText('Score Points')).toBeInTheDocument();
      expect(screen.getByText('Categories Explored')).toBeInTheDocument();

      fireEvent.click(statsButton());
      expect(screen.queryByText('Your Statistics')).not.toBeInTheDocument();
      expect(screen.queryByText('Total Questions')).not.toBeInTheDocument();
    });

    it('should not render charts when there are no category stats', () => {
      render(<App />);

      fireEvent.click(statsButton());

      expect(screen.queryByText('Questions by Category')).not.toBeInTheDocument();
      expect(screen.queryByText('Category Distribution')).not.toBeInTheDocument();
    });

    it('should render charts when category stats exist', () => {
      localStorage.setItem('categoryStats', JSON.stringify({ General: 2, Science: 1 }));
      render(<App />);

      fireEvent.click(statsButton());

      expect(screen.getByText('Questions by Category')).toBeInTheDocument();
      expect(screen.getByText('Category Distribution')).toBeInTheDocument();
      expect(screen.getByText('Categories Explored').previousSibling).toHaveTextContent('2');
    });

    it('should clear all history and stats when confirmed in the dashboard', () => {
      localStorage.setItem('streak', '4');
      seedHistory([makeItem()]);
      confirmSpy.mockReturnValue(true);
      render(<App />);
      expect(screen.getByText(/Question History \(1\)/)).toBeInTheDocument();

      fireEvent.click(statsButton());
      fireEvent.click(screen.getByRole('button', { name: 'Clear All' }));

      expect(confirmSpy).toHaveBeenCalled();
      expect(clearSpy).toHaveBeenCalled();
      expect(screen.queryByText(/Question History/)).not.toBeInTheDocument();
      expect(screen.getByText('0 Streak')).toBeInTheDocument();
    });

    it('should not clear data when confirm is cancelled', () => {
      localStorage.setItem('streak', '4');
      seedHistory([makeItem()]);
      confirmSpy.mockReturnValue(false);
      render(<App />);

      fireEvent.click(statsButton());
      fireEvent.click(screen.getByRole('button', { name: 'Clear All' }));

      expect(clearSpy).not.toHaveBeenCalled();
      expect(screen.getByText(/Question History \(1\)/)).toBeInTheDocument();
      expect(screen.getByText('4 Streak')).toBeInTheDocument();
    });
  });

  describe('history rendering', () => {
    it('should render history newest-first', () => {
      seedHistory([
        makeItem({ question: 'Older question' }),
        makeItem({ question: 'Newer question' }),
      ]);
      render(<App />);

      const entries = screen.getAllByText(/^Q: /).map((el) => el.textContent);

      expect(entries).toHaveLength(2);
      expect(entries[0]).toContain('Newer question');
      expect(entries[1]).toContain('Older question');
    });

    it('should truncate long answers to 200 characters followed by ellipsis', () => {
      seedHistory([makeItem({ answer: 'x'.repeat(250) })]);
      render(<App />);

      expect(screen.getByText(`A: ${'x'.repeat(200)}...`)).toBeInTheDocument();
      expect(screen.queryByText(`A: ${'x'.repeat(250)}...`)).not.toBeInTheDocument();
    });
  });
});